name: CI

# on: [disabled]
on: workflow_dispatch

permissions:
  contents: read

jobs:
  shell:
    if: false
    runs-on: macos-15
    steps:
      - run: echo "disabled"

  test:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "disabled"
